# Generated by Django 5.0.2 on 2024-03-29 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='issue title', max_length=255)),
                ('description', models.TextField(help_text='description of issue')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('TASK', 'Task')], default='BUG', help_text='tag of issue', max_length=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', help_text='Statuts issue', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, help_text='issue author', on_delete=django.db.models.deletion.CASCADE, related_name='issue_authors', to=settings.AUTH_USER_MODEL, verbose_name='issue author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('name', models.CharField(help_text='comment name', max_length=100, verbose_name='comment name')),
                ('description', models.TextField(help_text='comment body', verbose_name='comment body')),
                ('issue_url', models.URLField(blank=True, verbose_name='issue_link')),
                ('author', models.ForeignKey(blank=True, help_text='comment author', on_delete=django.db.models.deletion.CASCADE, related_name='comment_authors', to=settings.AUTH_USER_MODEL, verbose_name='comment author')),
                ('issue', models.ForeignKey(blank=True, help_text='Issue associated with comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.issue', verbose_name='related issue')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of project', max_length=255)),
                ('project_type', models.CharField(choices=[('back-end', 'Back-end'), ('front-end', 'Front-end'), ('iOS', 'iOS'), ('Android', 'Android')], help_text='Type of project', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description  project')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('author', models.ForeignKey(blank=True, help_text='project author', on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to=settings.AUTH_USER_MODEL, verbose_name='project author')),
                ('contributors', models.ManyToManyField(help_text='project contributors', related_name='contributions', through='project.Contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(help_text='Project with associated issue', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='project.project'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(help_text='Project to which the contributor contributes', on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relationship', to='project.project'),
        ),
    ]
